name: preprocessing

on:
  push:
    branches:
      - main

jobs:
  preprocesing:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python Version 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.7"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run preprocessing script
      run: |
        python preprocessing/automate_Alya.py

    - name: Commit preprocessing
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "GithubActions: updated preprocessed dataset"
        file_pattern: "preprocessing/*"
